<a href="https://colab.research.google.com/github/victor-onoja/DeepLearningLearning/blob/main/Copy_of_Intro_to_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to NumPy and Linear Algebra

## Row Vectors and Column Vectors

In [ ]:
import numpy as np
# while we introduced NumPy arrays as single-bracketed,
# double brackets will help us understand the ideas of linear algebra
double_bracket_row_vector = np.array([[34, 22, 11]])
double_bracket_row_vector

In [ ]:
# notice the shape
double_bracket_row_vector.shape

In [ ]:
# we can use this same idea to create column vectors
# inside the first pair of brackets, each set of brackets represents a new row
# each of the following elements belongs to the same column
column_vector = np.array([[1],[2],[3]])
column_vector

In [ ]:
column_vector.shape

## Coding a Matrix



In [ ]:
# to represent matrices in numpy, we also use double brackets
matrix = np.array([[2,1],[4,3]])
matrix

In [ ]:
matrix.shape

## Selecting Elements Out of a Matrix

In [ ]:
# unlike in our math notation, in numpy the matrices are zero-indexed
print("first row in the matrix: ", matrix[0])
print("second row in the matrix: ", matrix[1])
print("first column in the matrix: ", matrix[:, 0])
print("second column in the matrix: ", matrix[:, 1])
print("element in the first row, second column: ", matrix[0,1])
print("element in second row, second column: ", matrix[1,1])

## Adding Incompatible Matrices

In [ ]:
# what do you think will happen if we try adding the two matrices below?
matrix_one = np.array([[2,1],[4,3]])
matrix_two = np.array([[1,2,5], [5,3,2]])

# uncomment the line below and run the code block
# matrix_one+matrix_two

# Matrix Multiplication

## Multiplying Vectors

The way we multiply two vectors is almost identical to the way we used the dot product in the first course. The chief difference is that now we'll be paying attention to each vector's shape: we must multiply a row vector with a column vector that has a compatible shape.

In [ ]:
import numpy as np

row_vector = np.array([[1, 2, 3]])
column_vector = np.array([[4],[-5],[6]])

print(row_vector)
print(column_vector)

In [ ]:
product_vector = np.dot(row_vector, column_vector)
product_vector

## Multiplying Matrices

In [ ]:
A = np.array([[3,2,1],[0, -2, 4]])
B = np.array([[2,1],[-1,3],[5,4]])
print(A)
print(B)

NumPy uses the `.dot()` method to multiply matrices, too.

In [ ]:
product_matrix = np.dot(A,B)
product_matrix

In [ ]:
product_matrix.shape

## Matrix Compatibility

### First Example

In [ ]:
A = np.array([[3,2,3,4],[0,-2,4,8]])
B = np.array([[2,1],[-1,3],[4,3],[5,4]])
# do you think these matrices are compatible?
print(A)
print(B)
# why not look at their shape?
print(A.shape)
print(B.shape)

In [ ]:
product_matrix = np.dot(A,B)
print(product_matrix)
print(product_matrix.shape)

### Second Example

In [ ]:
# let's try one more example
C = np.array([[3,2,3],[0,-2,4]])
D = np.array([[2,1],[-1,3],[4,3],[5,4]])
# do you think these matrices are compatible?
print(C)
print(D)
# why not look at their shape?
print(C.shape)
print(D.shape)

In [ ]:
# let's take a look at what colab says when we try to multiply them
# uncomment all the lines of code below to find out
# protip: highlight multiple lines of text and press Ctrl/Cmd + / to comment or uncomment them all in one go.

# product_matrix = np.dot(C,D)
# print(product_matrix)
# print(product_matrix.shape)

# Rules and Identity

### Matrices Are Associative

In [ ]:
import numpy as np
A = np.array([[1,2],[4,5]])
B = np.array([[2,3],[5,6]])
C = np.array([[7,8],[9,10]])

product_1 = np.dot(np.dot(A,B),C)
print(product_1)
product_2 = np.dot(A, np.dot(B,C))
print(product_2)

### Matrices Are *Not* Commutative

In [ ]:
D = np.array([[1,2],[3,4],[5,6]])
E = np.array([[2,3,4],[5,6,7]])

D_times_E = np.dot(D,E)
E_times_D = np.dot(E,D)

print(D_times_E)
print(E_times_D)

### Identity Matrices

In [ ]:
# notice these output floats by default
np.identity(3)

In [ ]:
# you can override this by passing the dtype parameter
np.identity(3, dtype=int)

### Multiplying Identity Matrices

In [ ]:
import numpy as np
F = np.array([[1,2,3,4],[5,4,3,2]])
F

In [ ]:
F_I = np.identity(4, dtype=int)
F_times_I = np.dot(F,F_I)

print(F_times_I)

In [ ]:
G = np.array([[2,3], [3,2],[5,4]])
G

In [ ]:
G_I = np.identity(3, dtype=int)

I_times_G = np.dot(G_I,G)
print(I_times_G)

# Inverses and Transposition

## Obtaining the Matrix Inverse

In [ ]:
import numpy as np

X = np.array([[1, 8, 3], [1, -5, -9], [1, 3, 2]])
X

array([[ 1,  8,  3],
       [ 1, -5, -9],
       [ 1,  3,  2]])

In [ ]:
Xinv = np.linalg.inv(X)
Xinv

array([[-0.36170213,  0.14893617,  1.21276596],
       [ 0.23404255,  0.0212766 , -0.25531915],
       [-0.17021277, -0.10638298,  0.27659574]])

Now let's confirm that $X^{-1} \cdot X$ returns $I$.

In [ ]:
np.dot(Xinv, X)
# because NumPy is forced to eventually round up in its inverse calculations, we may get very small values where there should be zeroes.
# for example, 4.44e-16 is 4.44 X 10^(-16).
# for our purposes, any number times 10 raised to ^-16 can be treated as zero!

array([[1.00000000e+00, 4.44089210e-16, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.11022302e-16, 1.00000000e+00]])

## Singular and Non-Square Matrices

In [ ]:
singular_X = np.array([[-6, 2], [-12, 4]])
singular_X

array([[ -6,   2],
       [-12,   4]])

In [ ]:
# uncomment the line below to see the error message for a singular matrix
np.linalg.inv(singular_X)

LinAlgError: Singular matrix

In [ ]:
rectangular_X = np.array([[4,9],[9,8],[4,1]])

# uncomment the line below to see the error message for non-square matrices
np.linalg.inv(rectangular_X)

LinAlgError: Last 2 dimensions of the array must be square

## Transposing Matrices

In [ ]:
A = np.array([[3,4],[5,9],[1,8]])
A

array([[3, 4],
       [5, 9],
       [1, 8]])

In [ ]:
A_T = A.T
A_T

array([[3, 5, 1],
       [4, 9, 8]])

In [ ]:
print("The shape of A: ", A.shape)
print("The shape of A_T: ",A_T.shape)

The shape of A:  (3, 2)
The shape of A_T:  (2, 3)


## Isolating $w$

To isolate $w$ in $Xw = y$, we'd perform the following calculations:

$$Xw = y$$
$$X^{-1}Xw = X^{-1}y$$
$$Iw = X^{-1}y$$
$$w = X^{-1}y$$



In [ ]:
X = np.array([[1, 8, 3], [1, -5, -9], [1, 3, 2]])
y = np.array([[2], [7], [8]])

If we know both $X$ and $y$, seen above, we can solve for $w$ using the following code.

In [ ]:
# w = what do we write here to isolate w?
w = np.dot(np.linalg.inv(X),y)
print(w)

[[10.0212766 ]
 [-1.42553191]
 [ 1.12765957]]


Now let's confirm $Xw$ gets us $y$.

In [ ]:
Xw = np.dot(X,w)
print("Xw:")
print(Xw)
print("y:")
print(y)

Xw:
[[2.]
 [7.]
 [8.]]
y:
[[2]
 [7]
 [8]]


Neat, right? This is just one example of the many useful techniques you can apply, now that you've got a grasp on the basics of linear algebra.

In [ ]:
import numpy as np
x = np.array([[1] ,[4]])
w = np.array([[4],[3]])
np.dot(w.T,x)

array([[16]])